name: CI
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    container: nixos/nix:2.3.6
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/cachix-action@v6
        with:
          name: mrkkrp
          skipPush: true
      - name: Build the environment
        run: |
          nix-shell --attr site --pure --run true
          nix-env -f default.nix -iA netlify-cli
          nix-env -f default.nix -iA jq
      - name: Push to Cachix
        run: |
          nix-store -qR --include-outputs $(nix-instantiate --attr site default.nix) | cachix push mrkkrp
          nix-store -qR --include-outputs $(nix-instantiate --attr netlify-cli default.nix) | cachix push mrkkrp
        env:
          CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      - name: Build the site
        run: |
          if [ "$GITHUB_REF" = "refs/heads/master" ]
          then nix-build --attr site
          else nix-build --attr site-preview
          fi
      - name: Deploy to Netlify
        id: deploy
        run: |
          [ "$GITHUB_REF" = "refs/heads/master" ] && flags==--prod
          # Netlify does not see a symlink as a directory, so we have to
          # copy the contents.
          cp -R result/ publish/
          netlify deploy $flags --json | tee result.json
          echo -e "\n::set-output name=deploy_url::$(jq -r .deploy_url result.json)"
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      - name: Add commit status
        uses: Sibz/github-status-action@v1.1.0
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event.pull_request.head.sha || github.sha }}
          context: deploy/netlify
          description: Deploy preview ready
          state: success
          target_url: ${{ steps.deploy.outputs.deploy_url }}
