name: CI
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  ormolu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/run-ormolu@v14
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: ormolu
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
      - uses: cachix/cachix-action@v13
        with:
          name: markkarpov-com
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build the environment
        run: |
          nix shell '.#site'
          nix build '.#netlify-cli'
      - name: Build the site
        run: |
          if [ "$GITHUB_REF" = "refs/heads/master" ]
          then nix build '.#site'
          else nix build '.#site-preview'
          fi
          # Netlify does not see a symlink as a directory, so we have to
          # copy the contents.
          cp -R result/ publish/
      - name: Deploy to Netlify (preview)
        if: github.ref != 'refs/heads/master'
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: ./publish
          netlify-config-path: ./netlify.toml
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-pull-request-comment: true
          enable-commit-comment: false
          enable-commit-status: true
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      - name: Deploy to Netlify (production)
        if: github.ref == 'refs/heads/master'
        run: |
          nix run '.#netlify' -- deploy --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
