name: CI
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  ormolu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mrkkrp/ormolu-action@v10
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: ormolu
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
      - uses: cachix/cachix-action@v12
        with:
          name: mrkkrp
          skipPush: true
      - name: Build the environment
        run: |
          nix shell '.#site'
          nix build '.#jq'
          nix build '.#netlify-cli'
      - name: Push to Cachix
        run: |
          nix build --json '.#jq' | nix run '.#jq' -- -r '.[].outputs | to_entries[].value' | cachix push mrkkrp
          nix build --json '.#netlify-cli' |nix run '.#jq' -- -r '.[].outputs | to_entries[].value' | cachix push mrkkrp
          nix-store -qR --include-outputs $(nix build --json '.#site' | nix run '.#jq' -- -r '.[].drvPath') | cachix push mrkkrp
        env:
          CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      - name: Build the site
        run: |
          if [ "$GITHUB_REF" = "refs/heads/master" ]
          then nix build '.#site'
          else nix build '.#site-preview'
          fi
          # Netlify does not see a symlink as a directory, so we have to
          # copy the contents.
          cp -R result/ publish/
      - name: Deploy to Netlify (preview)
        if: github.ref != 'refs/heads/master'
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: ./publish
          netlify-config-path: ./netlify.toml
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-pull-request-comment: true
          enable-commit-comment: false
          enable-commit-status: true
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      - name: Deploy to Netlify (production)
        if: github.ref == 'refs/heads/master'
        run: |
          nix run '.#netlify' -- deploy --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
