name: CI
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  ormolu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mrkkrp/ormolu-action@v8
  build:
    runs-on: ubuntu-latest
    needs: ormolu
    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v15
      - uses: cachix/cachix-action@v10
        with:
          name: mrkkrp
          skipPush: true
      - name: Build the environment
        run: |
          nix shell '.#site'
          nix build '.#jq'
          nix build '.#netlify-cli'
      - name: Push to Cachix
        run: |
          nix build --json '.#jq' | nix run '.#jq' -- -r '.[].outputs | to_entries[].value' | cachix push mrkkrp
          nix build --json '.#netlify-cli' |nix run '.#jq' -- -r '.[].outputs | to_entries[].value' | cachix push mrkkrp
          nix-store -qR --include-outputs $(nix build --json '.#site' | nix run '.#jq' -- -r '.[].drvPath') | cachix push mrkkrp
        env:
          CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      - name: Build the site
        run: |
          if [ "$GITHUB_REF" = "refs/heads/master" ]
          then nix build '.#site'
          else nix build '.#site-preview'
          fi
      - name: Deploy to Netlify
        id: deploy
        run: |
          [ "$GITHUB_REF" = "refs/heads/master" ] && flags=--prod
          # Netlify does not see a symlink as a directory, so we have to
          # copy the contents.
          cp -R result/ publish/
          nix run '.#netlify' -- deploy $flags --json | tee result.json
          echo -e "\n::set-output name=deploy_url::$(nix run '.#jq' -- -r .deploy_url result.json)"
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      - name: Add commit status
        uses: Sibz/github-status-action@v1.1.6
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event.pull_request.head.sha || github.sha }}
          context: deploy/netlify
          description: Deploy preview ready
          state: success
          target_url: ${{ steps.deploy.outputs.deploy_url }}
